"""fix cascade delete

Revision ID: 958773dd1dcb
Revises: ca845326461c
Create Date: 2026-04-06 20:22:59.072737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958773dd1dcb'
down_revision = 'ca845326461c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.String(length=20), nullable=False),
    sa.Column('response', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checklist_items.check_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'check_id', name='uq_session_check')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_responses')
    # ### end Alembic commands ###
