"""add test_session

Revision ID: b97768bbe914
Revises: bc88d495a27a
Create Date: 2026-04-11 03:34:21.774590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97768bbe914'
down_revision = 'bc88d495a27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_id', sa.String(length=20), nullable=False),
    sa.Column('dimension', sa.Enum('Fluency', 'Coherence', 'GrammarAccuracy', 'GrammarRange', 'LexicalRange', 'LexicalPrecision', 'PronunciationSound', 'PronunciationProsody', 'Interaction', name='checklist_dimension_enum'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('typical_cefr_floor', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_id')
    )
    op.create_table('skill_nodes',
    sa.Column('skill_id', sa.String(length=50), nullable=False),
    sa.Column('skill_domain', sa.Enum('grammar', 'vocabulary', 'phonology', 'discourse', 'listening', 'reading', 'writing', name='skill_domain_enum'), nullable=False),
    sa.Column('cefr_target', sa.String(length=10), nullable=False),
    sa.Column('difficulty_weight', sa.Float(), nullable=False),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('typical_tasks', sa.Text(), nullable=True),
    sa.Column('speaking_environments', sa.Text(), nullable=True),
    sa.Column('accent_constraints', sa.Text(), nullable=True),
    sa.Column('target_level', sa.String(length=10), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('test_purpose', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('target_cefr', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.Column('vocab_targets', sa.Text(), nullable=False),
    sa.Column('distractor_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advised_vocab_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('situation', sa.String(length=200), nullable=True),
    sa.Column('priority_weight', sa.Float(), nullable=False),
    sa.Column('is_multiword', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_module', sa.Enum('Reporting', 'Advising', 'Testing', name='source_module_enum'), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('polarity', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('machine_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_prereqs',
    sa.Column('skill_id', sa.String(length=50), nullable=False),
    sa.Column('prereq_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['prereq_id'], ['skill_nodes.skill_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_nodes.skill_id'], ),
    sa.PrimaryKeyConstraint('skill_id', 'prereq_id')
    )
    op.create_table('student_skill_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.String(length=50), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('error_streak', sa.Integer(), nullable=False),
    sa.Column('success_streak', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_nodes.skill_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'skill_id', name='uq_student_skill')
    )
    op.create_table('test_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('overall_result', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.String(length=20), nullable=False),
    sa.Column('response', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checklist_items.check_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'check_id', name='uq_session_check')
    )
    op.create_table('evidence_skill_tags',
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.String(length=50), nullable=False),
    sa.Column('teacher_override', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_events.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_nodes.skill_id'], ),
    sa.PrimaryKeyConstraint('evidence_id', 'skill_id')
    )
    op.create_table('test_session_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('student_answer', sa.String(length=10), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['test_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_session_results')
    op.drop_table('evidence_skill_tags')
    op.drop_table('checklist_responses')
    op.drop_table('test_sessions')
    op.drop_table('student_skill_states')
    op.drop_table('skill_prereqs')
    op.drop_table('evidence_events')
    op.drop_table('advised_vocab_items')
    op.drop_table('test_items')
    op.drop_table('students')
    op.drop_table('skill_nodes')
    op.drop_table('checklist_items')
    # ### end Alembic commands ###
