"""add resolved_at to evidence_skill_tags

Revision ID: bc88d495a27a
Revises: 958773dd1dcb
Create Date: 2026-04-06 22:05:59.283687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc88d495a27a'
down_revision = '958773dd1dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_skill_tags', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_skill_tags', 'resolved_at')
    # ### end Alembic commands ###
