"""add checklist_items

Revision ID: ca845326461c
Revises: a5f38a4fc31b
Create Date: 2026-04-06 20:08:04.227762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca845326461c'
down_revision = 'a5f38a4fc31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_id', sa.String(length=20), nullable=False),
    sa.Column('dimension', sa.Enum('Fluency', 'Coherence', 'GrammarAccuracy', 'GrammarRange', 'LexicalRange', 'LexicalPrecision', 'PronunciationSound', 'PronunciationProsody', 'Interaction', name='checklist_dimension_enum'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('typical_cefr_floor', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_items')
    # ### end Alembic commands ###
